### ISSUE TITLE
Asset import failed when importing an SVG file from Vectornator

### ISSUE THREAD

**Issue by SiarheiPilat** [Unity-Technologies/vector-graphics-samples#20]
When importing an SVG file made with Vectornator (iPad app for vector graphics), I am getting the following two errors. First one:

Asset import failed, "Assets/New Document 1.svg" > SVGFormatException: SVG Error (line 18, character 2): Missing number at 8 in path specification
Unity.VectorGraphics.SVGAttribParser.ParsePath (Unity.VectorGraphics.XmlReaderIterator+Node node) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:2529)
Unity.VectorGraphics.SVGDocument.path () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:642)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:319)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:320)
Unity.VectorGraphics.SVGDocument.svg () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:1170)
Unity.VectorGraphics.SVGDocument.Import () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:264)
Unity.VectorGraphics.SVGParser.ImportSVG (System.IO.TextReader textReader, Unity.VectorGraphics.ViewportOptions viewportOptions, System.Single dpi, System.Single pixelsPerUnit, System.Int32 windowWidth, System.Int32 windowHeight) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:110)
Unity.VectorGraphics.Editor.SVGImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Editor/SVGImporter.cs:274)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <3b74787e58694cdda2c241162159b3b7>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

The second one:

SVGFormatException: SVG Error (line 18, character 2): Missing number at 8 in path specification
Unity.VectorGraphics.SVGAttribParser.ParsePath (Unity.VectorGraphics.XmlReaderIterator+Node node) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:2529)
Unity.VectorGraphics.SVGDocument.path () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:642)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:319)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:320)
Unity.VectorGraphics.SVGDocument.svg () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:1170)
Unity.VectorGraphics.SVGDocument.Import () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:264)
Unity.VectorGraphics.SVGParser.ImportSVG (System.IO.TextReader textReader, Unity.VectorGraphics.ViewportOptions viewportOptions, System.Single dpi, System.Single pixelsPerUnit, System.Int32 windowWidth, System.Int32 windowHeight) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Runtime/SVGParser.cs:110)
Unity.VectorGraphics.Editor.SVGImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.11/Editor/SVGImporter.cs:274)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <3b74787e58694cdda2c241162159b3b7>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Tried with 2019.3.0f1 and 2019.1.2f1

**Comment by dentedpixel** [comment]
This is still a problem for me as well! Vectornator is such a great program, I would really like this to be fixed and I can't identify anything wrong with the XML...

**Comment by dentedpixel** [comment]
In case anyone else runs into this issue, I have had some success with using Inkscape (beta) https://inkscape.org/release/inkscape-1.0beta2/mac-os-x/1010-1015/dl/ to re-export the SVG using the optimized SVG settings.

**Comment by mcoted** [comment]
If you still have issues with this, I recommend to file an official Unity bug report (Help > Report a Bug...). Thanks!
