### ISSUE TITLE
Could not load .svg in unity.

### ISSUE THREAD

**Issue by umresh** [Unity-Technologies/vector-graphics-samples#21]
Hi, I have an svg created by a plugin and I could not load it in unity. But its loaded in browser.

Using : Unity 2019.2 in Android Platform.

[sample.zip](https://github.com/Unity-Technologies/vector-graphics-samples/files/4039689/sample.zip)

**Comment by Blocovin** [comment]
We use poppler PDF library to convert PDF to svg and we can't load  svg in unity too.

[sample-plan.zip](https://github.com/Unity-Technologies/vector-graphics-samples/files/4393573/sample-plan.zip)

We got this error :
`NullReferenceException: Object reference not set to an instance of an object
Unity.VectorGraphics.SVGAttribParser.ParseFill (Unity.VectorGraphics.XmlReaderIterator+Node node, Unity.VectorGraphics.SVGDictionary dict, Unity.VectorGraphics.SVGPostponedFills postponedFills, Unity.VectorGraphics.SVGStyleResolver styles, Unity.VectorGraphics.Inheritance inheritance, System.Boolean& isDefaultFill) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:2584)
Unity.VectorGraphics.SVGDocument.ResolveReferencedNode (Unity.VectorGraphics.SceneNode referencedNode, Unity.VectorGraphics.SVGDocument+NodeReferenceData refData, System.Boolean isDeferred) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:1325)
Unity.VectorGraphics.SVGDocument.use () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:1258)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:319)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:320)
Unity.VectorGraphics.SVGDocument.ParseChildren (Unity.VectorGraphics.XmlReaderIterator+Node node, System.String nodeName) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:320)
Unity.VectorGraphics.SVGDocument.svg () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:1170)
Unity.VectorGraphics.SVGDocument.Import () (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:264)
Unity.VectorGraphics.SVGParser.ImportSVG (System.IO.TextReader textReader, Unity.VectorGraphics.ViewportOptions viewportOptions, System.Single dpi, System.Single pixelsPerUnit, System.Int32 windowWidth, System.Int32 windowHeight) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:110)
Unity.VectorGraphics.SVGParser.ImportSVG (System.IO.TextReader textReader, System.Single dpi, System.Single pixelsPerUnit, System.Int32 windowWidth, System.Int32 windowHeight, System.Boolean clipViewport) (at Library/PackageCache/com.unity.vectorgraphics@2.0.0-preview.12/Runtime/SVGParser.cs:68)
SVGRuntimeLoad.Start () (at Assets/RuntimeDemo/SVGRuntimeLoad.cs:41)`

**Comment by mcoted** [comment]
This has been reported a while ago, and we introduced a bunch of fixes since then. If you still have issues, I recommend to file an official bug report (Help > Report a Bug...). Thanks!
