### ISSUE TITLE
Display SVG files with code

### ISSUE THREAD

**Issue by TunTin** [Unity-Technologies/vector-graphics-samples#26]
Currently, I have 1 question to ask you as follows:
I have 1 3D scene and 1 2D panel inside that 3D scene and I need to add many SVG file to that panel with code and more I need to customize color and size for that SVG file as I want with code, You can you give me the solution, thank you very much

**Comment by Antonio-Iliev** [comment]
I think you can find some helpful information in the documentation: https://docs.unity3d.com/Packages/com.unity.vectorgraphics@2.0/manual/index.html
For overall resizing and overall colour changes, you can use the Unity component (RecTransform for resizing) and SVGImage (Color for colour) attached to the panel. 
Also, you can add SVG files runtime to the SVGImage component.  You can store them in the Resource folder and load them as you needed as Sprite.
This scenario is the simplest. You can extend the logic.

**Comment by mcoted** [comment]
When calling SVGParser.ImportSVG(), you'll get a SceneInfo with the NodeIDs list, which will store SVG nodes that have an `id="something"` attribute. You can get these nodes and modify the shapes.

Example:
https://forum.unity.com/threads/unity-ui-svg-support-script.551254/page-2#post-4364425

**Comment by TunTin** [comment]
Awesome, thanks!

===== Gửi từ Gmail của Nguyễn Tùng Anh =====

Vào 2:15 SA, Th 4, 25 thg 8, 2021 Martin Côté ***@***.***> đã
viết:
