### ISSUE TITLE
Can't be seen in Unity UI

### ISSUE THREAD

**Issue by jonryborbevobling** [Unity-Technologies/vector-graphics-samples#4]
I need help how to use the SVG in Canvas UI. I tried experimenting and it when I used it in Image, it can't be seen.

**Comment by mihakrajnc** [comment]
From what I can tell, it doesn't work (yet?) with Unity UI. Couldn't get it to work either.

**Comment by mcoted** [comment]
From our investigation, this is a limitation of the UI system which doesn't support tight sprites (they are always converted to rectangles).  The SVGImporter generates tight sprites, so they are incompatible with the UI system.

Unfortunately, it seems this will have to be fixed in the UI system.  I'll get in touch with the UI team.

**Comment by dbltnk** [comment]
Adding to this. I managed to show my SVG as a sprite component but I could not use it properly with the Image (Script) component in UnityUI. Image accepts the SVG sprite but even if you hack the reference to the Unlit_Vector material into te material slot for Image then the sprite still cannot be seen. And that means I cannot do sprit switches via the Button component etc.

Is there an ETA on this, @mcoted? We're just on the brink of moving a new game over to a vector-based art pipeline but that only works if we can keep on using UnityUI.

**Comment by mcoted** [comment]
> Is there an ETA on this, @mcoted? We're just on the brink of moving a new game over to a vector-based art pipeline but that only works if we can keep on using UnityUI.

Unfortunately, no.  I can't even guarantee that this limitation will be fixed (not my call, just the feedback I received.)

I can think of an alternative if you want to go with multi-resolution SVG and still use the Canvas UI.  Some users chose to generate textures from SVG at runtime, using tessellation options based on the device it's running on.  We provide helper methods to render textures from SVG files.  You could even build texture atlases at runtime to enable sprite batching.  You can contact me if you want to pursue that approach and need help.

**Comment by dbltnk** [comment]
Thanks for the reply, @mcoted, much appreciated! We'll consider that or even going a mixed route.

Out of interest: Is this based on technical limitations on the Unity-UI-side of things?

**Comment by mcoted** [comment]
> Out of interest: Is this based on technical limitations on the Unity-UI-side of things?

@dbltnk Yes absolutely.  I'm not an expert with the internals of Unity-UI, but my understanding is that it was designed for textured sprites.  Our sprites are textureless and I think this breaks some of the Unity-UI assumptions (there was quite a bit of work involved by the 2D team to make textureless work with the sprite system).

**Comment by garrynewman** [comment]
Would like this to work too, even if it's just a case of importing the svg as a texture.

**Comment by mcoted** [comment]
Version 1.0.0-preview.19 comes with an "SVG Image" UI component which makes it possible to use SVG sprites in the UI.  See this for more details: https://forum.unity.com/threads/unity-ui-svg-support-script.551254/

**Comment by dbltnk** [comment]
Thank you @mcoted, we'll experiment with it!
