### ISSUE TITLE
SVG Importer Editor Improvements

### ISSUE THREAD

**Issue by Frozenfire92** [Unity-Technologies/vector-graphics-samples#6]
- Multi object edit
- Copy/paste settings
- Reset doesn't reset to default values
- Undo support

![image](https://user-images.githubusercontent.com/5893112/40578135-3ea1c58e-60e5-11e8-9068-61519c4fbe50.png)

**Comment by mcoted** [comment]
The latest version 1.0.0-preview.19 has many improvements regarding multi-object editing, please have a look!
