### ISSUE TITLE
Fix gitignore

### ISSUE THREAD

**Issue by Frozenfire92** [Unity-Technologies/vector-graphics-samples#7]
Because of the .gitignore ingnoring `ProjectSettings` the sample can't be opened through unity hub

From the [docs:](https://docs.unity3d.com/Manual/ExternalVersionControlSystemSupport.html)

> When checking the project into a version control system, you should add the Assets, Packages and the ProjectSettings directories to the system.

I've used this in the past as a sane default https://github.com/github/gitignore/blob/master/Unity.gitignore

**Comment by mcoted** [comment]
Thank you!  Fixed in 5c41e9bb
